name: .NET

on:
  push:
    branches: [ project-page ]
  pull_request:
    branches: [ project-page ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      working-directory: Client
      run: dotnet publish -c Release -o ../release
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: release/wwwroot # The folder the action should deploy.
